### ISSUE TITLE
Doesn't work on iOS/iPadOS 18.1 beta 5

### ISSUE THREAD

**Issue by PavlychevV** [leminlimez/Nugget-Mobile#10]
Stuck at "idevicebackup2 exited with code -205"; "heartbeat success"

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/70210139-5cf1-4827-8d81-d6e6b8dec198">

**Comment by leminlimez** [comment]
"Should work on all versions iOS 16.0 - 18.1 beta 4"
patched in beta 5
