### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by emr0913** [leminlimez/Nugget-Mobile#25]
APPLYING
06:55:31 [TRACE] minimuxer::muxer: Handling ListDevices
Tweak pages being applied: [Nugget.TweakPage.MobileGestalt, Nugget.TweakPage.FeatureFlags, Nugget.TweakPage.Eligibility]
06:55:36 [INFO] minimuxer::heartbeat: Heartbeat success!
06:55:46 [INFO] minimuxer::heartbeat: Heartbeat success!
Executing args: ["idevicebackup2", "-n", "restore", "--no-reboot", "--system", "/var/mobile/Containers/Data/Application/E1C771FD-5102-4190-8B49-7AE004D95388/Documents/"]
06:55:53 [TRACE] minimuxer::muxer: Handling ListDevices
Backup directory is "/var/mobile/Containers/Data/Application/E1C771FD-5102-4190-8B49-7AE004D95388/Documents/"
06:55:53 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:53 [TRACE] minimuxer::muxer: Handling ReadBUID
06:55:53 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
06:55:53 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:54 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:55 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:55 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Started "com.apple.mobilebackup2" service on port 49186.
06:55:56 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Negotiated Protocol Version 2.1
Reading Info.plist from backup.
06:55:57 [INFO] minimuxer::heartbeat: Heartbeat success!
06:55:57 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:57 [TRACE] minimuxer::muxer: Handling ReadBUID
06:55:57 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
06:55:57 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:58 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:58 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:58 [TRACE] minimuxer::muxer: Handling ReadBUID
06:55:58 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
06:55:58 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:59 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:59 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:55:59 [TRACE] minimuxer::muxer: Handling ReadBUID
06:55:59 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
06:55:59 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:56:00 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Starting Restore...
Restoring system files: Yes
Rebooting after restore: No
Don't copy backup: Yes
Preserve settings of device: Yes
Remove items that are not restored: No
Backup password: No
No Applications in Info.plist, skipping creation of RestoreApplications.plist
Wrote RestoreApplications.plist
Sending '00008030-001A6CD022DA402E/Status.plist' (488 Bytes)
Sending '00008030-001A6CD022DA402E/Manifest.plist' (2.2 KB)
Sending '00008030-001A6CD022DA402E/Manifest.mbdb' (1.2 KB)
ErrorCode 205: Domain name cannot contain a slash (MBErrorDomain/205)
Restore Failed (Error Code 205).
06:56:02 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:56:03 [TRACE] minimuxer::muxer: Handling ReadBUID
06:56:03 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
06:56:03 [TRACE] minimuxer::muxer: Handling ReadPairRecord
06:56:03 [TRACE] minimuxer::muxer: Handling ReadPairRecord
idevicebackup2 exited with code -205
06:56:08 [INFO] minimuxer::heartbeat: Heartbeat success!
06:56:18 [INFO] minimuxer::heartbeat: Heartbeat success!
06:56:28 [INFO] minimuxer::heartbeat: Heartbeat success!
06:56:39 [INFO] minimuxer::heartbeat: Heartbeat success!
06:56:49 [INFO] minimuxer::heartbeat: Heartbeat success!

**Comment by leminlimez** [comment]
ios 18.1 beta 5 is not supported
